baseurl = "/"
languageCode = "en-us"
title = "Nix Theme"
theme = "hugo-theme-nix"

[params]
  GithubID = "DanielRSnell"
  TwitterID = "@Dninja757"
  LinkedInID = "your_linkedin"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  Name = "Daniel R. Snell"
  HeaderUsername = "Hi"
  HeaderHostname = "DanielSnell.Ninja"
  Email = "Hi@DanielSnell.Ninja"
  About = " Software Engineer & Growth Strategy Expert"
  ProfilePicture = "https://pbs.twimg.com/profile_images/485564678039302144/Fjxv6IbQ.png"
  GoogleAnalytics = "your_google_analytics_id"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/post"
